## Python Guia 2


# < > - Guia 02 Python
## Ejercicio 1

In [21]:
x = np.zeros((8,8),dtype=int)
x[0::7,0:8] = 1
x[1:7,0::7] = 1
print(x)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


## Ejercicio 3

In [54]:
def cartesians(vectores):
    
    for element in itertools.product(*vectores):
        print(element)
        
cartesians(([1, 2, 3],[4, 5],[6, 7]))

(1, 4, 6)
(1, 4, 7)
(1, 5, 6)
(1, 5, 7)
(2, 4, 6)
(2, 4, 7)
(2, 5, 6)
(2, 5, 7)
(3, 4, 6)
(3, 4, 7)
(3, 5, 6)
(3, 5, 7)


## Ejercicio 2

In [107]:
import numpy as np

def valor_mas_cercano(z, x):
    z = np.asarray(z)
    idx = (np.abs(z - x)).argmin()
    return z[idx]
x = 0.5

z = np.random.uniform(0,1,5)
print("Matriz: ",z)
print("valor mas cercano a ", x, ":",valor_mas_cercano(z, 0.5))



Matriz:  [0.8099897  0.34415059 0.96522705 0.83874071 0.11764763]
valor mas cercano a  0.5 : 0.34415058677130606


In [97]:
import numpy as np
def cartesians(vecfunc):
    
    list = np.stack([item for item in itertools.product(*vecfunc)]) 
    print(list)   
    
print(cartesians(([1, 2, 3],[4, 5],[6, 7],[8,9])))

[[1 4 6 8]
 [1 4 6 9]
 [1 4 7 8]
 [1 4 7 9]
 [1 5 6 8]
 [1 5 6 9]
 [1 5 7 8]
 [1 5 7 9]
 [2 4 6 8]
 [2 4 6 9]
 [2 4 7 8]
 [2 4 7 9]
 [2 5 6 8]
 [2 5 6 9]
 [2 5 7 8]
 [2 5 7 9]
 [3 4 6 8]
 [3 4 6 9]
 [3 4 7 8]
 [3 4 7 9]
 [3 5 6 8]
 [3 5 6 9]
 [3 5 7 8]
 [3 5 7 9]]
None


In [283]:
import numpy as np

def valor_mas_cercano(z, x):
    z = np.asarray(z)
    idx = (np.abs(z - x)).argmin()
    return z[idx]

valor_mas_cercano(z,0.5)

z = np.random.uniform(0,1,5)
print("Matriz: ",z)
print("valor mas cercano a ", x, ":",valor_mas_cercano(z, 0.5))


Matriz:  [0.7998249  0.16002563 0.60884973 0.67094233 0.93421769]
valor mas cercano a  0.5 : 0.6088497316607413


In [100]:
import numpy as np
x = np.ones((3,3))

In [5]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
x = np.zeros((8,8),dtype=int)

In [7]:
x


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [31]:
import itertools

somelists = [
   [1, 2, 3],
   [4, 5],
   [6, 7]
]

def cartesians(somelists):
    
    for element in itertools.product(*somelists):
        print(element)

In [63]:
def vector(a,b):
    if (a>b): return a
    else: return b
vecfunc = np.vectorize(vector)

def cartesians(vecfunc):
    
    for element in itertools.product(*vecfunc):
        print(element)
        
print(cartesians(([1, 2, 3],[4, 5],[6, 7],[8,9])))

(1, 4, 6, 8)
(1, 4, 6, 9)
(1, 4, 7, 8)
(1, 4, 7, 9)
(1, 5, 6, 8)
(1, 5, 6, 9)
(1, 5, 7, 8)
(1, 5, 7, 9)
(2, 4, 6, 8)
(2, 4, 6, 9)
(2, 4, 7, 8)
(2, 4, 7, 9)
(2, 5, 6, 8)
(2, 5, 6, 9)
(2, 5, 7, 8)
(2, 5, 7, 9)
(3, 4, 6, 8)
(3, 4, 6, 9)
(3, 4, 7, 8)
(3, 4, 7, 9)
(3, 5, 6, 8)
(3, 5, 6, 9)
(3, 5, 7, 8)
(3, 5, 7, 9)
None


In [57]:
x = [5,4,1,7,6]
res = x.zfill(3) 

AttributeError: 'list' object has no attribute 'zfill'

In [94]:
import numpy as np
def cartesians(vecfunc):
    
    list = np.stack([item for item in itertools.product(*vecfunc)]) 
    print(list)   
    
print(cartesians(([1, 2, 3],[4, 5],[6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]
None


In [128]:
a = np.array([5,4,1,7,6])


b = np.zeros((5),dtype=int)
np.hstack((a,b)).reshape(a.shape[0],-1)

array([[5, 4],
       [1, 7],
       [6, 0],
       [0, 0],
       [0, 0]])

In [217]:
import numpy as np

a = np.array([5,4,1,7,6])
b = 3

def intercalar(a, b):
    
    z = np.asarray(a)
    y = np.zeros(b)
    c =  np.concatenate((z,y))
    print(c)

intercalar(a,b)

[5. 4. 1. 7. 6. 0. 0. 0.]


In [213]:
c


array([5., 4., 1., 7., 6., 0., 0., 0.])

In [219]:
number = 15 # number of zeroes to add
df= np.array([5,4,1,7,6])
df['ID'] = df['ID'].str.zfill(number)

str.zfill(width)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [260]:
import numpy as np

a = np.array([5,4,1,7,6])
b = 3

def intercalar_ceros(a, b):
    
    z = np.asarray(a)
    y = np.zeros(b)
    c =  [v for elt in a for v in (y,elt)]
    print(c)
    

    
    
intercalar_ceros(a,b)

[array([0., 0., 0.]), 5, array([0., 0., 0.]), 4, array([0., 0., 0.]), 1, array([0., 0., 0.]), 7, array([0., 0., 0.]), 6]


In [278]:
a = np.array([5,4,1,7,6])
b = 3
y = np.zeros(b)
a[-4] + y

array([4., 4., 4.])